### ISSUE TITLE
Error on 'Object.module.exports.create' when create multi tasks

### ISSUE THREAD

**Issue by fancyoung** [sgentle/phantomjs-node#116]
I add a function to fetch webpage's title.
```
  phantom.create(function(ph) {
    ph.createPage(function(page) {
      page.open(url, function(status) {
        page.evaluate(function() {
          return document.title;
        }, function(result) {
          console.log(result);
          ph.exit();
        });
      });
    });
  }, {port: 12302});
```

But when this function was requested twice in the same time, error showns
```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: listen EADDRINUSE
    at errnoException (net.js:901:11)
    at Server._listen2 (net.js:1039:14)
    at listen (net.js:1061:10)
    at Server.listen (net.js:1127:5)
    at Object.module.exports.create (/.../node_modules/phantom/phantom.js:90:18)
...
19 Oct 12:37:08 - [nodemon] exception in nodemon killing node
Error: read ECONNRESET
    at errnoException (net.js:901:11)
    at Pipe.onread (net.js:556:19)
19 Oct 12:37:08 - [nodemon] app crashed - waiting for file changes before starting...
^C19 Oct 12:50:20 - [nodemon] exiting
```

I think it's the port conflict problem, but I don't think change port each time is a good idea (the number of threads depends on online request).
It's there any better way to solve this, such as make the create function as queue?

**Comment by amir20** [comment]
Cleaning out old bugs.
