### ISSUE TITLE
abnormal phantomjs exit code: -1073741819

### ISSUE THREAD

**Issue by bayun2** [sgentle/phantomjs-node#137]
when i use phantomjs,There is an error occurred.
assert.js:92
  throw new assert.AssertionError({
        ^
AssertionError: abnormal phantomjs exit code: -1073741819
    at Console.assert (console.js:102:23)
    at ChildProcess.<anonymous> (D:\carcrawler\node_modules\phantom\phantom.js:3
1:22)
    at ChildProcess.EventEmitter.emit (events.js:117:20)
    at Process.ChildProcess._handle.onexit (child_process.js:789:12)

This represents what the error code  -1073741819  ？？

**Comment by btomashvili** [comment]
Same issue   ... is any solution for this problem ?

**Comment by c0bra** [comment]
:+1:

**Comment by amir20** [comment]
Cleaning out old bugs. If it is still valid, let's reopen.
