### ISSUE TITLE
Cannot find module 'qs'

### ISSUE THREAD

**Issue by mrvisser** [sgentle/phantomjs-node#178]
Originally reported here: https://github.com/Medium/phantomjs/issues/176

Installing on Travis-ci. Error:
```
phantomjs@1.9.7-8 install /home/travis/build/foo/bar/node_modules/phantomjs
node install.js
module.js:340
throw err;
^
Error: Cannot find module 'qs'
at Function.Module._resolveFilename (module.js:338:15)
at Function.Module._load (module.js:280:25)
at Module.require (module.js:364:17)
at require (module.js:380:17)
at Object. (/home/travis/build/foo/bar/node_modules/request/request.js:8:10)
at Module._compile (module.js:456:26)
at Object.Module._extensions..js (module.js:474:10)
at Module.load (module.js:356:32)
at Function.Module._load (module.js:312:12)
at Module.require (module.js:364:17)
npm ERR! phantomjs@1.9.7-8 install: node install.js
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the phantomjs@1.9.7-8 install script.
npm ERR! This is most likely a problem with the phantomjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR! node install.js
npm ERR! You can get their info via:
npm ERR! npm owner ls phantomjs
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 2.6.32-042stab079.5
npm ERR! command "/home/travis/.nvm/v0.10.26/bin/node" "/home/travis/.nvm/v0.10.26/bin/npm" "install"
npm ERR! cwd /home/travis/build/foo/bar
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.3
npm ERR! code ELIFECYCLE
```

**Comment by amir20** [comment]
Cleaning out old bugs. If it is still valid, let's reopen.
