### ISSUE TITLE
dlopen issue

### ISSUE THREAD

**Issue by ryanstout** [sgentle/phantomjs-node#191]
This may be related to me running phantom-node in node-webkit, but I thought I would mention it here incase someone can point me in the right direction.  I'm getting the following when I try to run phantom-node:

```Uncaught node.js Error 

Error: dlopen(/Users/ryanstout/Sites/resumeblaster/meteor/node-webkit/node_modules/phantom/node_modules/dnode/node_modules/weak/build/Release/weakref.node, 1): no suitable image found.  Did find:
/Users/ryanstout/Sites/resumeblaster/meteor/node-webkit/node_modules/phantom/node_modules/dnode/node_modules/weak/build/Release/weakref.node: mach-o, but wrong architecture
    at Module.load (module.js:352:32)
    at Function.Module._load (module.js:308:12)
    at Module.require (module.js:360:17)
    at require (module.js:376:17)
    at bindings (/Users/ryanstout/Sites/resumeblaster/meteor/node-webkit/node_modules/phantom/node_modules/dnode/node_modules/weak/node_modules/bindings/bindings.js:76:44)
    at Object.eval (/Users/ryanstout/Sites/resumeblaster/meteor/node-webkit/node_modules/phantom/node_modules/dnode/node_modules/weak/lib/weak.js:7:35)
    at Module._compile (module.js:452:26)
    at Object.Module._extensions..js (module.js:470:10)
    at Module.load (module.js:352:32)
    at Function.Module._load (module.js:308:12)
```

The interesting part is things work if I add the following config option:

```
    dnodeOpts: {
      weak: false
    }
```

Anyone have any ideas on why this is happening?  Thanks

**Comment by amir20** [comment]
Closing since there is no official support for `node-webkit`

**Comment by TrejGun** [comment]
have same with
```
node -v
v5.2.0
```
