### ISSUE TITLE
Error: Module version mismatch. Expected 43, got 14.

### ISSUE THREAD

**Issue by miguelmota** [sgentle/phantomjs-node#279]
```bash
$ node index.js
/Users/moogs/Development/demo/node_modules/phantom/node_modules/dnode/node_modules/weak/node_modules/bindings/bindings.js:83
        throw e
              ^
Error: Module version mismatch. Expected 43, got 14.
    at Error (native)
    at Module.load (module.js:339:32)
    at Function.Module._load (module.js:294:12)
    at Module.require (module.js:349:17)
    at require (module.js:368:17)
    at bindings (/Users/moogs/Development/demo/node_modules/phantom/node_modules/dnode/node_modules/weak/node_modules/bindings/bin
dings.js:76:44)
    at Object.<anonymous> (/Users/moogs/Development/demo/node_modules/phantom/node_modules/dnode/node_modules/weak/lib/weak.js:7:3
5)
    at Module._compile (module.js:444:26)
    at Object.Module._extensions..js (module.js:462:10)
    at Module.load (module.js:339:32)

```

`index.js`

```javascript
var phantom = require('phantom');

phantom.create(function (ph) {
  ph.createPage(function (page) {
    page.open("http://www.google.com", function (status) {
      console.log("opened google? ", status);
      page.evaluate(function () { return document.title; }, function (result) {
        console.log('Page title is ' + result);
        ph.exit();
      });
    });
  });
});
```

**Comment by alexbaumgertner** [comment]
Have same issue with iojs. (With node v0.12.2 works ok).
Try to run with node js instead iojs

**Comment by DinisCruz** [comment]
@miguelmota where you able to solve this, I have the same problem

**Comment by DustinDSchultz** [comment]
Why was this closed? I'm having the same issue after upgrading to Node 4.2, then 5.0.

**Comment by amir20** [comment]
I probably made a mistake. Can you reopen?

**Comment by bruno-serfe** [comment]
Why this is closed? I've the same issue with weak and phantom Error: Module version mismatch. Expected 46, got 14. Is any other issue reported regarding this?

**Comment by syzer** [comment]
+1

**Comment by danielronnkvist** [comment]
Any solutions to this problem?

**Comment by syzer** [comment]
yup.... dont use fantom.... :trollface:

**Comment by amir20** [comment]
This error is so old that I am not sure about the relevancy of it. Since then, I have rewritten the module which uses different libs. If it happens with the new version then open a new issue. Otherwise the old version is not supported anymore.
