### ISSUE TITLE
Ubuntu 12.04.2 LTS npm install Error

### ISSUE THREAD

**Issue by loretoparisi** [sgentle/phantomjs-node#286]
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 12.04.2 LTS
Release:	12.04
Codename:	precise

```bash
$ sudo npm install phantom
npm http GET https://registry.npmjs.org/phantom

npm ERR! Error: failed to fetch from registry: phantom
npm ERR!     at /usr/share/npm/lib/utils/npm-registry-client/get.js:139:12
npm ERR!     at cb (/usr/share/npm/lib/utils/npm-registry-client/request.js:31:9)
npm ERR!     at Request._callback (/usr/share/npm/lib/utils/npm-registry-client/request.js:136:18)
npm ERR!     at Request.callback (/usr/lib/nodejs/request/main.js:119:22)
npm ERR!     at Request.<anonymous> (/usr/lib/nodejs/request/main.js:212:58)
npm ERR!     at Request.emit (events.js:88:20)
npm ERR!     at ClientRequest.<anonymous> (/usr/lib/nodejs/request/main.js:412:12)
npm ERR!     at ClientRequest.emit (events.js:67:17)
npm ERR!     at HTTPParser.onIncoming (http.js:1261:11)
npm ERR!     at HTTPParser.onHeadersComplete (http.js:102:31)
npm ERR! You may report this log at:
npm ERR!     <http://bugs.debian.org/npm>
npm ERR! or use
npm ERR!     reportbug --attach /home/musixmatch/npm-debug.log npm
npm ERR! 
npm ERR! System Linux 3.2.0-45-virtual
npm ERR! command "node" "/usr/bin/npm" "install" "phantom"
npm ERR! cwd /home/musixmatch
npm ERR! node -v v0.6.12
npm ERR! npm -v 1.1.4
npm ERR! message failed to fetch from registry: phantom
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/musixmatch/npm-debug.log
npm not ok
```

**Comment by loretoparisi** [comment]
It seems that npm failed to get the default registry:

```npm config set registry http://registry.npmjs.org/```
