### ISSUE TITLE
Phantomjs page.OnError Override Crash

### ISSUE THREAD

**Issue by loretoparisi** [sgentle/phantomjs-node#287]
It seems it does not override the default ```pageOneError```

```javascript
page.onError = function(msg, trace) {
                var msgStack = ['ERROR: ' + msg];
                if (trace && trace.length) {
                    msgStack.push('TRACE:');
                    trace.forEach(function(t) {
                        msgStack.push(' -> ' + t.file + ': ' + t.line + (t.function ? ' (in function "' + t.function + '")' : ''));
                    });
                }
                // uncomment to log into the console
                // console.error(msgStack.join('\n'));
            };
```

**Comment by loretoparisi** [comment]
I came out with the set

 ```javascript
page.set('onError', function(msg, trace) {
                var msgStack = ['ERROR: ' + msg];
                if (trace && trace.length) {
                    msgStack.push('TRACE:');
                    trace.forEach(function(t) {
                        msgStack.push(' -> ' + t.file + ': ' + t.line + (t.function ? ' (in function "' + t.function + '")' : ''));
                    });
                }
                // uncomment to log into the console
                // console.error(msgStack.join('\n'));
            })
```

The problem that this causes crashes occasionally:

```bash
assert.js:92
  throw new assert.AssertionError({
        ^
AssertionError: abnormal phantomjs exit code: 1
    at Console.assert (console.js:102:23)
    at ChildProcess.<anonymous> (/Volumes/MacHDD2/Developmemt/node_modules/phantom/phantom.js:153:28)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at Process.ChildProcess._handle.onexit (child_process.js:789:12)
```

**Comment by vgrinko** [comment]
@loretoparisi, I confirm the crash. Did you find any workaround?

**Comment by loretoparisi** [comment]
@vgrinko not at moment, I was not able to override the on Error.
As far as I know, of all these handlers

```javascript
registerHandlers : function(page, handlers) {
		if(handlers.onLoadStarted) page.set('onLoadStarted',handlers.onLoadStarted)
		if(handlers.onLoadFinished) page.set('onLoadFinished',handlers.onLoadFinished)
		if(handlers.resourceError) page.set('onResourceError', handlers.resourceError)
		if(handlers.onResourceRequested) page.set('onResourceRequested',handlers.onResourceRequested)
		if(handlers.onResourceReceived) page.set('onResourceReceived',handlers.onResourceReceived)
		if(handlers.onNavigationRequested) page.set('onNavigationRequested',handlers.onNavigationRequested)
		if(handlers.onError) page.set('onError',handlers.onError)

	}
```

only the onError causes the crash.
